/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CourseCourseIndexRouteImport } from './routes/course.$course.index'
import { Route as CourseCourseSemesterIndexRouteImport } from './routes/course.$course.$semester.index'
import { Route as CourseCourseSemesterSubjectRouteImport } from './routes/course.$course.$semester.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIndexRoute = CourseCourseIndexRouteImport.update({
  id: '/course/$course/',
  path: '/course/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseSemesterIndexRoute =
  CourseCourseSemesterIndexRouteImport.update({
    id: '/course/$course/$semester/',
    path: '/course/$course/$semester/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseCourseSemesterSubjectRoute =
  CourseCourseSemesterSubjectRouteImport.update({
    id: '/course/$course/$semester/$subject',
    path: '/course/$course/$semester/$subject',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course/': typeof CourseCourseIndexRoute
  '/course/$course/$semester/$subject': typeof CourseCourseSemesterSubjectRoute
  '/course/$course/$semester/': typeof CourseCourseSemesterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course': typeof CourseCourseIndexRoute
  '/course/$course/$semester/$subject': typeof CourseCourseSemesterSubjectRoute
  '/course/$course/$semester': typeof CourseCourseSemesterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course/': typeof CourseCourseIndexRoute
  '/course/$course/$semester/$subject': typeof CourseCourseSemesterSubjectRoute
  '/course/$course/$semester/': typeof CourseCourseSemesterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/course/$course/'
    | '/course/$course/$semester/$subject'
    | '/course/$course/$semester/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/course/$course'
    | '/course/$course/$semester/$subject'
    | '/course/$course/$semester'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/course/$course/'
    | '/course/$course/$semester/$subject'
    | '/course/$course/$semester/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookmarksRoute: typeof BookmarksRoute
  CourseCourseIndexRoute: typeof CourseCourseIndexRoute
  CourseCourseSemesterSubjectRoute: typeof CourseCourseSemesterSubjectRoute
  CourseCourseSemesterIndexRoute: typeof CourseCourseSemesterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/': {
      id: '/course/$course/'
      path: '/course/$course'
      fullPath: '/course/$course/'
      preLoaderRoute: typeof CourseCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/$semester/': {
      id: '/course/$course/$semester/'
      path: '/course/$course/$semester'
      fullPath: '/course/$course/$semester/'
      preLoaderRoute: typeof CourseCourseSemesterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/$semester/$subject': {
      id: '/course/$course/$semester/$subject'
      path: '/course/$course/$semester/$subject'
      fullPath: '/course/$course/$semester/$subject'
      preLoaderRoute: typeof CourseCourseSemesterSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookmarksRoute: BookmarksRoute,
  CourseCourseIndexRoute: CourseCourseIndexRoute,
  CourseCourseSemesterSubjectRoute: CourseCourseSemesterSubjectRoute,
  CourseCourseSemesterIndexRoute: CourseCourseSemesterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
