/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CourseCourseIndexRouteImport } from './routes/course.$course.index'
import { Route as CourseCourseSemesterRouteImport } from './routes/course.$course.$semester'
import { Route as CourseCourseSemesterIndexRouteImport } from './routes/course.$course.$semester.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIndexRoute = CourseCourseIndexRouteImport.update({
  id: '/course/$course/',
  path: '/course/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseSemesterRoute = CourseCourseSemesterRouteImport.update({
  id: '/course/$course/$semester',
  path: '/course/$course/$semester',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseSemesterIndexRoute =
  CourseCourseSemesterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CourseCourseSemesterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course/$semester': typeof CourseCourseSemesterRouteWithChildren
  '/course/$course/': typeof CourseCourseIndexRoute
  '/course/$course/$semester/': typeof CourseCourseSemesterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course': typeof CourseCourseIndexRoute
  '/course/$course/$semester': typeof CourseCourseSemesterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/course/$course/$semester': typeof CourseCourseSemesterRouteWithChildren
  '/course/$course/': typeof CourseCourseIndexRoute
  '/course/$course/$semester/': typeof CourseCourseSemesterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/course/$course/$semester'
    | '/course/$course/'
    | '/course/$course/$semester/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarks' | '/course/$course' | '/course/$course/$semester'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/course/$course/$semester'
    | '/course/$course/'
    | '/course/$course/$semester/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  CourseCourseSemesterRoute: typeof CourseCourseSemesterRouteWithChildren
  CourseCourseIndexRoute: typeof CourseCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/': {
      id: '/course/$course/'
      path: '/course/$course'
      fullPath: '/course/$course/'
      preLoaderRoute: typeof CourseCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/$semester': {
      id: '/course/$course/$semester'
      path: '/course/$course/$semester'
      fullPath: '/course/$course/$semester'
      preLoaderRoute: typeof CourseCourseSemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$course/$semester/': {
      id: '/course/$course/$semester/'
      path: '/'
      fullPath: '/course/$course/$semester/'
      preLoaderRoute: typeof CourseCourseSemesterIndexRouteImport
      parentRoute: typeof CourseCourseSemesterRoute
    }
  }
}

interface CourseCourseSemesterRouteChildren {
  CourseCourseSemesterIndexRoute: typeof CourseCourseSemesterIndexRoute
}

const CourseCourseSemesterRouteChildren: CourseCourseSemesterRouteChildren = {
  CourseCourseSemesterIndexRoute: CourseCourseSemesterIndexRoute,
}

const CourseCourseSemesterRouteWithChildren =
  CourseCourseSemesterRoute._addFileChildren(CourseCourseSemesterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  CourseCourseSemesterRoute: CourseCourseSemesterRouteWithChildren,
  CourseCourseIndexRoute: CourseCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
